export enum EHONOR_PREVIEW_PLACE {
  FIRST = 1,
  SECOND = 2,
  THIRD = 3,
}

export const AVATAR_HONOR_PREVIEW_SIZE: Record<EHONOR_PREVIEW_PLACE, number> = {
  [EHONOR_PREVIEW_PLACE.FIRST]: 110,
  [EHONOR_PREVIEW_PLACE.SECOND]: 96,
  [EHONOR_PREVIEW_PLACE.THIRD]: 84,
};

export const HONOR_CARD_MARGIN: Record<EHONOR_PREVIEW_PLACE, number> = {
  [EHONOR_PREVIEW_PLACE.FIRST]: 0,
  [EHONOR_PREVIEW_PLACE.SECOND]: 40,
  [EHONOR_PREVIEW_PLACE.THIRD]: 60,
};

export const HONOR_CARD_COLOR_BADGE: Record<EHONOR_PREVIEW_PLACE, string> = {
  [EHONOR_PREVIEW_PLACE.FIRST]: '#EDC850',
  [EHONOR_PREVIEW_PLACE.SECOND]: '#CCCCCC',
  [EHONOR_PREVIEW_PLACE.THIRD]: '#C38242',
};
